"""
base.py — BusBackend Abstract Base Class
========================================

Defines the storage contract that every ChaseOS agent bus backend must satisfy.

WHY THIS EXISTS
---------------
The original bus.py spoke SQLite directly. That works perfectly for local, single-machine
deployments — zero infrastructure, portable file, works offline. But ChaseOS is heading
toward a world where:

  - Multiple users run runtimes (OpenClaw, Hermes) on separate VPS machines
  - A mobile or web UI needs live push updates (WebSocket), not file polling
  - Multi-tenant deployments need auth and a real server process

SQLite cannot be shared over a network. Introducing a storage abstraction now means
the server backend can be swapped in later (Phase 10) with NO changes to handlers,
workflows, or the AOR engine. Only backend_loader.py changes.

TWO MODES — ONE INTERFACE
--------------------------
Local mode  (mode: local)   — SQLiteBackend. Default. Single machine. Zero infrastructure.
                               The vault's .chaseos/agent_bus.sqlite is the store.
                               This is the right choice for personal use, development, and
                               any deployment where all runtimes live on one machine.

Server mode (mode: server)  — ServerBackend (Phase 10). HTTP/WebSocket. Multi-machine.
                               VPS-capable. Enables mobile/web dashboards and N runtimes
                               across arbitrary machines. Requires a running ChaseOS server
                               process and a connection string in bus_config.yaml.

THE CONTRACT
------------
All BusBackend methods receive ONLY the data they need — vault_root is resolved at
construction time by the loader, not passed per-call. This keeps the interface clean
and lets server backends ignore the local filesystem entirely.

Implementations must be safe for concurrent reads. Writes are serialized at the
storage layer (SQLite WAL mode; server backend via the server process itself).

WHY ABC NOT PROTOCOL
--------------------
Python Protocols allow structural (duck-typed) satisfaction. ABCs require explicit
declaration. Here we want explicit declaration: a backend must consciously implement
this contract, not accidentally satisfy it. Violations surface at class definition
time, not silently at runtime when a method is missing.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any


class BackendInitError(RuntimeError):
    """Raised when a backend cannot initialize its storage.

    This is a hard failure — the bus cannot operate without storage.
    The caller (backend_loader) should surface this immediately rather than
    continuing with a broken backend.
    """


class BusBackend(ABC):
    """Storage contract for the ChaseOS agent coordination bus.

    Concrete implementations:
      SQLiteBackend  — local mode  (runtime/agent_bus/backends/sqlite_backend.py)
      ServerBackend  — server mode (Phase 10, not yet implemented)

    Instantiation: backends are created once per vault_root by
    backend_loader.get_backend() and cached for the process lifetime.
    Do not instantiate directly — always go through get_backend().

    All methods are synchronous. Server mode will use blocking HTTP calls
    internally, keeping the interface consistent across modes.
    """

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    @abstractmethod
    def init(self) -> None:
        """Initialize storage: create tables, apply schema, verify connectivity.

        Called once at backend instantiation by the loader. Must be idempotent:
        repeated calls on an already-initialized store must not corrupt data
        or raise errors. This is intentional — multiple processes may call
        init() on the same store concurrently at startup.

        Raises BackendInitError if storage cannot be initialized (disk full,
        network unreachable, bad credentials, schema mismatch, etc.).
        """

    # ── Task operations ───────────────────────────────────────────────────────

    @abstractmethod
    def create_task(
        self,
        *,
        task_id: str,
        run_id: str,
        sender: str,
        recipient: str,
        intent: str,
        priority: str,
        request: str,
        expected_output: str,
        depends_on: list[str],
        notes: str | None,
        expires_at: str | None,
        now_iso: str,
        ingress_context: dict[str, Any] | None = None,
        work_fingerprint: str | None = None,
        execution_constraints: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Persist a new task and its 'created' event.

        task_id and run_id are generated by the caller (bus.py) before this
        call — the backend does not generate IDs. This keeps ID generation
        logic centralized and consistent across backends.

        Returns: {'created': True, 'task_id': ..., 'run_id': ...,
                  'sender': ..., 'recipient': ...}
        On storage failure: {'created': False, 'reason': ..., 'task_id': ...}
        """

    @abstractmethod
    def list_tasks(
        self,
        *,
        recipient: str | None = None,
        status: str | None = None,
        owner: str | None = None,
    ) -> list[dict[str, Any]]:
        """Return tasks matching the given filters, ordered by created_at ASC.

        All filters are optional and additive (AND). An empty filter set
        returns all tasks. Tasks are returned as plain dicts with keys
        matching the schema column names.
        """

    @abstractmethod
    def get_task(self, task_id: str) -> dict[str, Any] | None:
        """Return a single task by task_id, or None if not found.

        This is the atomic read used before mutating operations (claim,
        update_status, reclaim). Server backends should implement this
        as a single GET request, not a filtered list call.
        """

    @abstractmethod
    def claim_task(
        self,
        *,
        task_id: str,
        runtime: str,
        now_iso: str,
        lane_guard: dict[str, Any] | None = None,
        runtime_instance_id: str | None = None,
    ) -> dict[str, Any]:
        """Atomically claim an open task for a runtime.

        Must be atomic: two runtimes racing to claim the same task must
        result in exactly one winner. SQLite handles this via exclusive
        write locking. Server backends must implement this as a
        compare-and-swap or a serialized endpoint.

        Backends must also enforce lane-aware claim arbitration inside the
        same serialized mutation path. If the runtime already owns active
        work in the same work_fingerprint, origin_message_id, or
        conversation_key lane, the claim must fail without updating the task.
        lane_guard is optional caller context; the stored task row remains
        the source of truth.

        Backends should persist runtime_instance_id into owner_instance when
        supplied or derivable from stored lane context. owner remains the
        runtime bus name; owner_instance identifies the control-surface lane.

        Returns: {'claimed': True/False, 'task_id': ..., ...}
        On failure (not open, wrong recipient, not found):
          {'claimed': False, 'reason': ..., 'task_id': ...}
        """

    @abstractmethod
    def update_task_status(
        self,
        *,
        task_id: str,
        runtime: str,
        status: str,
        event_type: str,
        message: str,
        artifacts: list[str] | None,
        now_iso: str,
    ) -> dict[str, Any]:
        """Update task status and append an event to its trail.

        The event trail is the bus's audit log — every status transition
        appends an immutable event. The trail must be append-only.

        Returns: {'updated': True/False, 'task_id': ..., 'status': ...}
        """

    # ── Heartbeat operations ──────────────────────────────────────────────────

    @abstractmethod
    def upsert_heartbeat(
        self,
        *,
        runtime: str,
        status: str,
        health: str,
        current_task_id: str | None,
        summary: str | None,
        now_iso: str,
        runtime_instance_id: str | None = None,
        heartbeat_scope: str = "runtime",
        control_surface: str | None = None,
        control_surface_key: str | None = None,
    ) -> dict[str, Any]:
        """Insert or update a runtime or runtime-instance liveness record.

        Heartbeats are the bus's liveness layer. A runtime that has not
        sent a heartbeat within its declared heartbeat_stale_seconds is
        considered stale and its tasks may be reclaimed.

        Backward-compatible callers may continue publishing runtime-scoped
        heartbeats only. Instance-aware callers should provide a stable
        runtime_instance_id and control-surface identity when liveness needs
        to distinguish multiple live ingress/control lanes for one runtime.

        Returns the heartbeat dict as stored.
        """

    @abstractmethod
    def list_heartbeats(self) -> list[dict[str, Any]]:
        """Return all current heartbeat records.

        Runtime-scoped and instance-scoped rows may coexist. Callers that need
        a runtime summary can reduce the returned rows by runtime and freshness.
        Returns a plain list of dicts.
        """

    # ── Maintenance operations ────────────────────────────────────────────────

    @abstractmethod
    def mark_stale_tasks(
        self,
        *,
        max_age_seconds: int,
        stale_runtimes: set[str],
        now_iso: str,
    ) -> dict[str, Any]:
        """Expire tasks owned by stale runtimes that exceed max_age_seconds.

        stale_runtimes: set of runtime bus_names already determined to be
          stale by the caller (bus.py resolves this via the router before
          calling here). The backend does not query heartbeats — staleness
          determination is the caller's responsibility.

        Returns:
          {'expired_count': int, 'task_ids': [...],
           'skipped_not_stale_count': int, 'skipped_not_stale_task_ids': [...],
           'stale_runtimes': [...], 'now': str}
        """

    @abstractmethod
    def reclaim_task(
        self,
        *,
        task_id: str,
        new_runtime: str,
        reason: str,
        now_iso: str,
    ) -> dict[str, Any]:
        """Re-open a task owned by a stale runtime for another runtime to claim.

        Only succeeds if:
          - The task exists and is in an active state
          - new_runtime is not the current owner (can't reclaim your own task)

        Does NOT check staleness — the caller must verify staleness before
        calling reclaim. This separation keeps reclaim atomic and avoids
        race conditions between staleness check and reclaim.

        Returns: {'reclaimed': True/False, 'task_id': ..., ...}
        """

    @abstractmethod
    def list_events(self, task_id: str) -> list[dict[str, Any]]:
        """Return all events for a task ordered by created_at ASC.

        Each event dict includes: event_id, task_id, run_id, sender,
        event_type, message, artifacts (list), created_at.
        Returns an empty list if the task has no events or does not exist.
        """
