"""Install-Safety Installer Orchestrator.

`prepare_install_session()` is the preflight-gated front door to actually installing
ChaseOS. It runs the read-only preflight, refuses to proceed when the result is
blocked, and for the safe fully-reversible path (coexist via WSL2 Ubuntu) it
generates a real, runnable setup script the operator reviews and runs themselves.

Doctrine compliance:
- This module is read-only against the host: it inspects, gates, and *writes setup
  artifacts to the vault* (a session record + a setup script). It NEVER executes a
  host mutation itself — running the generated script is the operator's explicit act.
- It will not generate an executable script for a destructive (same-disk) install.
  Same-disk stays manual, gated by the recovery-media gate + typed confirmation,
  consistent with Install-Safety-Preflight-Architecture (host mutation out of scope).
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from runtime.install_safety.preflight import run_preflight
from runtime.install_safety.report import (
    INTENT_EXTERNAL_DISK,
    INTENT_SAME_DISK,
    INTENT_SPARE_DISK,
    INTENT_VM,
)

# Map a declared intent to a safe-install mode id.
_MODE_BY_INTENT = {
    INTENT_VM: "coexist",
    INTENT_SPARE_DISK: "spare-disk",
    INTENT_EXTERNAL_DISK: "external-ssd",
    INTENT_SAME_DISK: "advanced-dual-boot",
}


def _wsl_setup_script(facts: dict) -> str:
    """Generate a runnable, fully-reversible WSL2 Ubuntu setup script."""
    inside = facts.get("running_inside_wsl") is True
    available = facts.get("wsl_available")
    ubuntu = facts.get("wsl_ubuntu_present")

    header = [
        "# ChaseOS Safe Install - Coexist via WSL2 Ubuntu (fully reversible)",
        "# Generated by `chaseos install-safety setup`. REVIEW before running.",
        "# This does NOT touch your partitions or your Windows install.",
        "# To undo completely later:  wsl --unregister Ubuntu",
        "",
    ]
    if inside:
        body = [
            "# You are already inside WSL Ubuntu - no setup needed.",
            "# Install ChaseOS here directly (clone the repo and run the CLI).",
        ]
    elif available and ubuntu:
        body = [
            "# WSL Ubuntu is already installed. Enter it and install ChaseOS there:",
            "wsl -d Ubuntu",
            "# Then, inside Ubuntu, install ChaseOS (clone the repo + run the CLI).",
        ]
    else:
        body = [
            "# Enable WSL and install Ubuntu (one command; reboots once):",
            "wsl --install -d Ubuntu",
            "# After the reboot and Ubuntu first-run user setup, enter Ubuntu:",
            "#   wsl -d Ubuntu",
            "# Then install ChaseOS inside Ubuntu (clone the repo + run the CLI).",
        ]
    return "\n".join(header + body) + "\n"


def _setup_artifact(intent: Optional[str], facts: dict) -> Optional[dict]:
    """Return a setup-script artifact for auto-scriptable safe modes, else None."""
    if intent == INTENT_VM:
        # "vm" intent is the coexist lane in this layer → WSL script.
        return {
            "filename_suffix": "setup-coexist-wsl.ps1",
            "language": "powershell",
            "content": _wsl_setup_script(facts),
            "reversible": True,
            "executes_host_mutation": True,  # running it installs WSL — reversible, operator-run
        }
    # Spare/external installs happen through the OS installer/ISO, not a script we can
    # safely generate; same-disk is destructive and intentionally never scripted here.
    return None


def _manual_steps(intent: Optional[str], preflight: dict) -> list[str]:
    if intent == INTENT_SPARE_DISK:
        return [
            "Download the ChaseOS / Linux installer ISO and write it to a USB.",
            "Boot the installer and select the SPARE disk only (never the Windows disk).",
            "Safest variant: physically disconnect the Windows disk during install.",
            "Capture a partition snapshot first: `chaseos install-safety snapshot`.",
        ]
    if intent == INTENT_EXTERNAL_DISK:
        return [
            "Write the ChaseOS / Linux installer ISO to a USB.",
            "Boot it and install to the EXTERNAL SSD/USB target only.",
            "Your internal OS disk is untouched; unplug the drive to remove the install.",
        ]
    if intent == INTENT_SAME_DISK:
        plan = preflight.get("install_plan") or {}
        return list(plan.get("steps") or [])
    return []


def prepare_install_session(
    *,
    intent: Optional[str] = None,
    backup_verified: Optional[bool] = None,
    recovery_usb: Optional[bool] = None,
    target_disk: Optional[int] = None,
    confirm_token: Optional[str] = None,
    facts: Optional[dict] = None,
    runner=None,
    system: Optional[str] = None,
) -> dict:
    """Run the preflight gate and prepare an install session.

    Returns a session dict. `status` is one of:
        - "choose-a-mode"      no intent declared
        - "blocked"            preflight blocked or recovery-media gate failed
        - "ready"              a safe path is prepared (script and/or manual steps)
        - "manual-advanced"    same-disk: gated, manual, not scripted
    `ready_to_run` is True only when a reviewed setup script is provided OR the path
    needs no host mutation. Running any emitted script is the operator's explicit act.
    """
    preflight = run_preflight(
        intent=intent, backup_verified=backup_verified, recovery_usb=recovery_usb,
        target_disk=target_disk, facts=facts, runner=runner, system=system,
    )
    norm_intent = preflight.get("intent")
    decision = preflight.get("decision")
    gate = preflight.get("recovery_media_gate") or {}
    plan = preflight.get("install_plan") or {}

    setup_script = None
    manual_steps: list[str] = []
    confirmation = None

    if not norm_intent:
        status = "choose-a-mode"
    elif decision == "blocked":
        status = "blocked"
    elif norm_intent == INTENT_SAME_DISK:
        # Destructive: never auto-scripted. Gated by recovery media + typed token.
        token = plan.get("confirmation_token")
        satisfied = bool(confirm_token) and confirm_token == token
        confirmation = {"required": True, "token": token, "satisfied": satisfied}
        manual_steps = _manual_steps(norm_intent, preflight)
        status = "manual-advanced"
    else:
        setup_script = _setup_artifact(norm_intent, facts=preflight.get("facts", {}))
        manual_steps = _manual_steps(norm_intent, preflight)
        status = "ready"

    ready_to_run = status == "ready"

    return {
        "read_only": True,
        "status": status,
        "decision": decision,
        "intent": norm_intent,
        "mode": _MODE_BY_INTENT.get(norm_intent),
        "ready_to_run": ready_to_run,
        "setup_script": setup_script,
        "manual_steps": manual_steps,
        "confirmation": confirmation,
        "recovery_media_gate": gate,
        "coexist": preflight.get("coexist"),
        "preflight": preflight,
    }


def write_install_session(
    session: dict,
    vault_root: str | Path,
    *,
    timestamp: str,
) -> dict:
    """Persist the session record (JSON) and any setup script to vault artifacts.

    Writes only to the vault (07_LOGS/Install-Safety/Install-Sessions/), never to a
    physical disk. `timestamp` is caller-supplied for deterministic filenames.
    """
    import json

    base = Path(vault_root) / "07_LOGS" / "Install-Safety" / "Install-Sessions"
    base.mkdir(parents=True, exist_ok=True)

    written: dict[str, str] = {}
    script = session.get("setup_script")
    if script and script.get("content"):
        script_name = f"{timestamp}-{script['filename_suffix']}"
        script_path = base / script_name
        script_path.write_text(script["content"], encoding="utf-8")
        written["setup_script"] = str(script_path)

    record = dict(session)
    record["written"] = written
    session_path = base / f"{timestamp}-install-session.json"
    session_path.write_text(json.dumps(record, indent=2), encoding="utf-8")
    written["session"] = str(session_path)
    return written


def render_install_session_text(session: dict) -> str:
    """Render an install session as a human-readable report."""
    lines: list[str] = []
    add = lines.append
    add("ChaseOS Installer Setup (read-only preparation; nothing was changed)")
    add("=" * 66)
    add(f"Declared intent : {session.get('intent') or '(none - choose a mode)'}")
    add(f"Mode            : {session.get('mode') or '-'}")
    add(f"Status          : {session.get('status')}")
    add(f"Ready to run    : {session.get('ready_to_run')}")
    add("")

    if session.get("status") == "blocked":
        add("INSTALL BLOCKED - resolve these before proceeding:")
        for b in session.get("preflight", {}).get("blockers", []):
            add(f"  ! {b}")
        gate = session.get("recovery_media_gate") or {}
        for m in gate.get("missing") or []:
            add(f"  ! MISSING: {m}")
        add("")
        coexist = session.get("coexist") or {}
        if coexist.get("recommended_action"):
            add("Safest alternative (coexist / WSL):")
            add(f"  {coexist['recommended_action']}")
            add("")
        return "\n".join(lines).rstrip() + "\n"

    if session.get("status") == "choose-a-mode":
        add("No install intent declared. Choose one of the safe modes:")
        for mode in session.get("preflight", {}).get("safe_install_modes", []):
            add(f"  - {mode['label']}")
        add("")
        return "\n".join(lines).rstrip() + "\n"

    confirmation = session.get("confirmation")
    if confirmation and confirmation.get("required"):
        state = "satisfied" if confirmation.get("satisfied") else "NOT satisfied"
        add(f"Typed confirmation: {state}")
        if not confirmation.get("satisfied"):
            add(f"  Re-run with --confirm-token {confirmation.get('token')}")
        add("")

    script = session.get("setup_script")
    if script:
        add(f"Generated setup script ({script['language']}, "
            f"{'reversible' if script.get('reversible') else 'NOT reversible'}):")
        add("-" * 66)
        for line in script["content"].splitlines():
            add(f"  {line}")
        add("-" * 66)
        add("Review the script above, then run it yourself. ChaseOS does not run it for you.")
        add("")

    if session.get("manual_steps"):
        add("Steps:")
        for i, step in enumerate(session["manual_steps"], 1):
            add(f"  {i}. {step}")
        add("")

    return "\n".join(lines).rstrip() + "\n"
