"""
runtime.operator_surface.approvals

Approval request/result management for FSOS execution.
The executor pauses when an approval gate is reached and resumes
only after an operator decision is recorded.

Approval model defined in: 06_AGENTS/Full-System-Operator-Surface.md Section 6.2
SOP: 04_SOPS/Full-System-Operator-Safety-SOP.md Section 3
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from runtime.operator_surface.contracts import ApprovalRecord


class ApprovalDenied(Exception):
    """Raised when an operator denies an approval gate. Execution halts."""
    def __init__(self, approval_id: str, step_index: int, action_type: str):
        self.approval_id = approval_id
        self.step_index = step_index
        self.action_type = action_type
        super().__init__(
            f"Operator denied approval for action '{action_type}' at step {step_index} "
            f"(approval_id={approval_id}). Execution halted."
        )


class ApprovalTimeout(Exception):
    """Raised when an approval gate times out without a response."""
    pass


@dataclass
class ApprovalRequest:
    """
    An outbound approval request generated by the FSOS executor.
    Emitted via AWAIT_APPROVAL event to OSRIL / operator surface.
    The executor blocks until a response is received.
    """
    approval_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    run_id: str = ""
    step_index: int = 0
    action_type: str = ""
    target: str = ""
    description: str = ""
    surface: str = ""
    risk_level: str = "HIGH"    # LOW | MEDIUM | HIGH | CRITICAL
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


@dataclass
class ApprovalResponse:
    """
    An inbound approval response from the operator.
    Received by the executor via CLI or OSRIL event bus.
    """
    approval_id: str
    decision: str   # "APPROVE" | "DENY"
    operator_note: str = ""
    responded_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class ApprovalStore:
    """
    In-memory store for pending approval requests within a single run.
    Thread-safe for single-threaded executor use (no concurrency within a run).

    In future: may be backed by a lightweight persistent store
    to support approval responses from OSRIL event bus across network.
    """

    def __init__(self):
        self._pending: dict[str, ApprovalRequest] = {}
        self._records: list[ApprovalRecord] = []

    def create_request(
        self,
        run_id: str,
        step_index: int,
        action_type: str,
        target: str,
        description: str,
        surface: str,
        risk_level: str = "HIGH",
    ) -> ApprovalRequest:
        req = ApprovalRequest(
            run_id=run_id,
            step_index=step_index,
            action_type=action_type,
            target=target,
            description=description,
            surface=surface,
            risk_level=risk_level,
        )
        self._pending[req.approval_id] = req
        return req

    def record_response(self, response: ApprovalResponse) -> ApprovalRecord:
        """
        Record an approval response. Returns the immutable ApprovalRecord.
        Removes the request from pending.
        Raises ApprovalDenied if decision is DENY.
        """
        req = self._pending.pop(response.approval_id, None)
        if req is None:
            raise ValueError(f"No pending approval request with id={response.approval_id}")

        record = ApprovalRecord(
            approval_id=response.approval_id,
            run_id=req.run_id,
            step_index=req.step_index,
            action_type=req.action_type,
            target=req.target,
            description=req.description,
            decision=response.decision,
            operator_note=response.operator_note,
            timestamp=response.responded_at,
        )
        self._records.append(record)

        if response.decision == "DENY":
            raise ApprovalDenied(
                approval_id=response.approval_id,
                step_index=req.step_index,
                action_type=req.action_type,
            )

        return record

    def get_all_records(self) -> list[ApprovalRecord]:
        return list(self._records)

    def has_pending(self) -> bool:
        return bool(self._pending)

    def get_pending_ids(self) -> list[str]:
        return list(self._pending.keys())
